### ISSUE TITLE
Unable to create conda environment

### ISSUE THREAD

**Issue by sukruc** [beer-asr/beer#101]
conda version: 4.8.2
Platform: Windows 10 64-bit

Using instructions as provided on README, conda env create command fails with following error:

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ncurses=6.1
  - pango=1.42.4
  - readline=7.0
  - fribidi=1.0.5
  - glib=2.56.2
  - graphviz=2.40.1
  - gettext=0.19.8.1
  - expat=2.2.6
  - harfbuzz=1.8.8
  - graphite2=1.3.12
  - libedit=3.1.20170329
  - fontconfig=2.13.0
 ```

**Comment by aatcili** [comment]
Having the same problem with conda 4.9.2

**Comment by lucasondel** [comment]
Hi, thanks for taking the time to report this issue. 

@aatcili Are you also using Windows ?

**Comment by lucasondel** [comment]
I have tried to re-install the environment from scratch on Linux (no Windows machine around) and there was no problem. 

The library that failed to install are typical Linux/Unix softwares so I have strong suspicion that this is a  Windows compatibility issue. 

I suppose you can solve it by using Windows' Linux subsytem instead of the default Windows shell. 

However, most of the recipes for AUD in beer assume a SGE-like environment, so I afraid you won't be able to run the recipes on windows. The notebook examples can probably run fine  though.
