### ISSUE TITLE
HMM doesn't fit Variational distribution of VAE

### ISSUE THREAD

**Issue by Baileyswu** [beer-asr/beer#86]
Hi, Iondel!
I’ve checked the result of HMM-VAE, there are some questions.
We know that VAE is used to extract features from high dimension to low one. Through the encoder of VAE, we can have its posteriors ([in this line](https://github.com/Baileyswu/beer/blob/f4cb652f0388f40767c620d85c55c06eb654a870/beer/models/vae.py#L40)). So if we put 600 dataset into the encoder, we will have 600 posteriors. We use the means as the new dataset, which will be the observation of HMM, the prior of VAE.
As you can see, the posterior mean can be covered by three normal distribution from HMM. But the variances of normal distribution stay large, which cannot fit the posterior means during the training process.
I think it’s quite strange because simple HMM can fit data well. There are no reasons that it crashes down when we introduce VAE.
I try to use another form of distribution to describe the posterior of VAE, but there are some troubles to substitute the NoramalDiagonalCovariance to NormalWishart or something. Yeah, that’s a biggest problem! There are no concrete documents about params, distributions, modelset, conjugate updates and so on ...... I feel dizzy when step into the embedded class. I will appreciate that you can provide some related theory or papers about these framework and models.
Anyway, thanks very much for your attention and help!
![hmm](https://user-images.githubusercontent.com/13285397/69160287-4a35f600-0b24-11ea-9ace-50fc8e6dfabb.png)

**Comment by Baileyswu** [comment]
After sampling data from posterior, we can get newdata which fit the HMM likelihood.
![bokeh_plot (8)](https://user-images.githubusercontent.com/13285397/69161712-8b2f0a00-0b26-11ea-837e-56a7cd20d19f.png)
so it's reasonable that hmm have such distributions.

**Comment by iondel** [comment]
The thread is closed but I'd like to add a couple of precisions. As you have realized, in the VAE-HMM model, the HMM does not model the posteriors' mean but the density formed from all the posteriors. Hence, that's why you see the HMM's emissions fit the sampled data and not just the means. 

Regarding your other comment, I agree that BEER has evolved to the state where it is difficult to use as there is no real documentation. Furthermore, technical documentation is not enough as the whole design of the software requires some theoretical knowledge about very specific machine learning algorithms. This theoretical background is also not easily assimilated/distributed since it is spread across many publications but, to my knowledge, has not been gather in a single textbook or similar support. 

Anyway, I'm glad BEER gathers the implementation of several unsupervised/low-resource speech learning algorithms (thanks again for the VAE part btw) andI hope it will serve as a starting point for other  people who work in this field.
