### ISSUE TITLE
Import failed for HSHMM

### ISSUE THREAD

**Issue by lucasondel** [beer-asr/beer#90]
Here is the error when trying to run `beer`:
`cannot import name 'setprior' from 'beer.cli.subcommands.hshmm'`

The problem comes from:
https://github.com/beer-asr/beer/blob/bdf49045e99f2115d7879947e9052107424cd2e6/beer/cli/subcommands/hshmm/__init__.py#L5

**Comment by bolajiy** [comment]
I see. I was cleaning up some unused functions and didn't reflect the changes in the init file. Fix incoming

**Comment by syfengcuhk** [comment]
A similar question in  importing:
`from . import mkphoneloopgraph`
In the file 

> https://github.com/beer-asr/beer/blob/master/beer/cli/subcommands/hshmm/__init__.py

`ImportError: cannot import name 'mkphoneloopgraph' from 'beer.cli.subcommands.hshmm'`

I suspect this line is not necessary? Because in the directory `beer/cli/subcommands/hshmm`, there is no python file `mkphoneloopgraph.py`.

Please check. THanks in advance.

**Comment by bolajiy** [comment]
Thanks @syfengcuhk You're right, the import statement is no longer necessary. I'll leave this issue open while I try to hunt down any other similar bugs, and I'll merge the fix asap. 
In the meantime, it's ok to just remove that line from __init__.py

**Comment by syfengcuhk** [comment]
> Thanks @syfengcuhk You're right, the import statement is no longer necessary. I'll leave this issue open while I try to hunt down any other similar bugs, and I'll merge the fix asap.
> In the meantime, it's ok to just remove that line from **init**.py

Okay great thanks
